### ISSUE TITLE
留名500 LIMIT 後新增的留名

### ISSUE THREAD

**Issue by hkg231560** [Saren-Arterius/datHKG#2]
1. 當留名數已達500 個, 新增留名不成功 (但 Toast message 話已留名)。另外maize APP 係可以加超過500個留名... (高登BUG??)
2. 當留名數已達500 個, 新bookmark 嘅POST (e.g. post id = 5767871) 會起留名頁面LOADING 果陣見到, LOAD 完就唔見咗.... 然後DELETE 返高登bookmark去500 以下, 再起datHKG bookmark 岩岩個POST (post id = 5767871) 係唔成功..

LOADING 果陣見到2個起500LIMIT後新加嘅bookmark
![1_loading](https://cloud.githubusercontent.com/assets/11830093/7018619/6837b3a0-dd39-11e4-8b6c-6b4f1a4307fe.PNG)

LOAD 完唔見咗 :O, 仲會LOCK 住2個POST, 清完bookmark 再加返都唔得
![2](https://cloud.githubusercontent.com/assets/11830093/7018618/683781a0-dd39-11e4-888c-f6603effb0c2.PNG)

**Comment by Saren-Arterius** [comment]
等我有500個留名先試呢個bug...

**Comment by Saren-Arterius** [comment]
另外知唔知如果你有500個留名，去桌面版高登禁留名掣，會出d咩message？

**Comment by hkg231560** [comment]
粒button 一樣SHOW 「名已留」，不過其實冇加到bookmark

**Comment by Saren-Arterius** [comment]
咁樣既話，只可以令個app唔去check之前有冇留過名
除非方丈大日check有冇爆500/同一個post之前有冇留名

**Comment by Saren-Arterius** [comment]
因為高登既垃圾設計，我唯有係唔係都send一次「留名」去高登server。
所以應該唔會再有類似bug發生。
